name: Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '!master'

jobs:
  build:
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    # 1.Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2    

    # 2.Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    # 3.build release
    - name: Create the app package
      run: msbuild Du.PMPage.Wpf.sln /p:Configuration=Release
